
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup and Run Docker Compose
    init: |
      unzip marketing-saas-stack.zip -d ./stack
      cd ./stack/marketing-saas-stack
      docker-compose up -d
    command: |
      echo "Your Marketing SaaS is running. Use Gitpod URLs to access services."
      gp ports list
ports:
  - port: 5678
    onOpen: open-preview
    description: n8n Automation
  - port: 3001
    onOpen: open-preview
    description: Postiz Campaigns
  - port: 8080
    onOpen: open-preview
    description: Mixpost Social Media
  - port: 8888
    onOpen: open-preview
    description: EspoCRM
  - port: 8000
    onOpen: open-preview
    description: PostHog Analytics
    